/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EnergyMixResponse,
  EnergyUsageWindowModel,
  GetOptimalWindowParams
} from '../generated.schemas';





export type getOptimalWindowResponse200 = {
  data: EnergyUsageWindowModel
  status: 200
}
    
export type getOptimalWindowResponseSuccess = (getOptimalWindowResponse200) & {
  headers: Headers;
};
;

export type getOptimalWindowResponse = (getOptimalWindowResponseSuccess)

export const getGetOptimalWindowUrl = (params: GetOptimalWindowParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8080/api/optimal-window?${stringifiedParams}` : `http://localhost:8080/api/optimal-window`
}

export const getOptimalWindow = async (params: GetOptimalWindowParams, options?: RequestInit): Promise<getOptimalWindowResponse> => {
  
  const res = await fetch(getGetOptimalWindowUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getOptimalWindowResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getOptimalWindowResponse
}





export const getGetOptimalWindowQueryKey = (params?: GetOptimalWindowParams,) => {
    return [
    `http://localhost:8080/api/optimal-window`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetOptimalWindowQueryOptions = <TData = Awaited<ReturnType<typeof getOptimalWindow>>, TError = unknown>(params: GetOptimalWindowParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOptimalWindow>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOptimalWindowQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOptimalWindow>>> = ({ signal }) => getOptimalWindow(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOptimalWindow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOptimalWindowQueryResult = NonNullable<Awaited<ReturnType<typeof getOptimalWindow>>>
export type GetOptimalWindowQueryError = unknown


export function useGetOptimalWindow<TData = Awaited<ReturnType<typeof getOptimalWindow>>, TError = unknown>(
 params: GetOptimalWindowParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOptimalWindow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOptimalWindow>>,
          TError,
          Awaited<ReturnType<typeof getOptimalWindow>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOptimalWindow<TData = Awaited<ReturnType<typeof getOptimalWindow>>, TError = unknown>(
 params: GetOptimalWindowParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOptimalWindow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOptimalWindow>>,
          TError,
          Awaited<ReturnType<typeof getOptimalWindow>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOptimalWindow<TData = Awaited<ReturnType<typeof getOptimalWindow>>, TError = unknown>(
 params: GetOptimalWindowParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOptimalWindow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetOptimalWindow<TData = Awaited<ReturnType<typeof getOptimalWindow>>, TError = unknown>(
 params: GetOptimalWindowParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOptimalWindow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOptimalWindowQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export type getEnergyMixResponse200 = {
  data: EnergyMixResponse
  status: 200
}
    
export type getEnergyMixResponseSuccess = (getEnergyMixResponse200) & {
  headers: Headers;
};
;

export type getEnergyMixResponse = (getEnergyMixResponseSuccess)

export const getGetEnergyMixUrl = () => {


  

  return `http://localhost:8080/api/energy-mix`
}

export const getEnergyMix = async ( options?: RequestInit): Promise<getEnergyMixResponse> => {
  
  const res = await fetch(getGetEnergyMixUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getEnergyMixResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getEnergyMixResponse
}





export const getGetEnergyMixQueryKey = () => {
    return [
    `http://localhost:8080/api/energy-mix`
    ] as const;
    }

    
export const getGetEnergyMixQueryOptions = <TData = Awaited<ReturnType<typeof getEnergyMix>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEnergyMix>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEnergyMixQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEnergyMix>>> = ({ signal }) => getEnergyMix({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEnergyMix>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEnergyMixQueryResult = NonNullable<Awaited<ReturnType<typeof getEnergyMix>>>
export type GetEnergyMixQueryError = unknown


export function useGetEnergyMix<TData = Awaited<ReturnType<typeof getEnergyMix>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEnergyMix>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEnergyMix>>,
          TError,
          Awaited<ReturnType<typeof getEnergyMix>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEnergyMix<TData = Awaited<ReturnType<typeof getEnergyMix>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEnergyMix>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEnergyMix>>,
          TError,
          Awaited<ReturnType<typeof getEnergyMix>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEnergyMix<TData = Awaited<ReturnType<typeof getEnergyMix>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEnergyMix>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetEnergyMix<TData = Awaited<ReturnType<typeof getEnergyMix>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEnergyMix>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEnergyMixQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




