/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export interface EnergyUsageWindowModel {
  from?: string;
  to?: string;
  cleanShare?: number;
}

export interface DailyEnergyMixModel {
  date?: string;
  generationMix?: EnergyMixElementModel[];
}

export interface EnergyMixElementModel {
  name?: string;
  share?: number;
}

export interface EnergyMixResponse {
  mixes?: DailyEnergyMixModel[];
}

export type GetOptimalWindowParams = {
/**
 * @minimum 1
 * @maximum 6
 */
window: number;
};

